const FALLBACK_PRODUCTS=[
{id:'firehouse',name:'The Firehouse',category:'pizza',price:1899,description:'Pepperoni, roasted peppers, jalapeño and hot honey.',image:'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=700&q=85',popular:true},
{id:'garden',name:'Garden Party',category:'pizza',price:1699,description:'Mushrooms, bell peppers, olives, onions and herbs.',image:'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=700&q=85'},
{id:'truffle',name:'Truffle Bianca',category:'pizza',price:2199,description:'Creamy white sauce, mozzarella, mushroom and truffle oil.',image:'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=700&q=85'},
{id:'bbq',name:'Smoky BBQ Chicken',category:'pizza',price:1999,description:'Smoked chicken, red onion, sweet BBQ and cheddar.',image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=700&q=85',popular:true},
{id:'garlic',name:'Garlic Bread',category:'sides',price:499,description:'Warm, buttery and finished with parsley.',image:'https://images.unsplash.com/photo-1573140401552-3fab0b24306f?auto=format&fit=crop&w=700&q=85'},
{id:'wings',name:'Hot Wings',category:'sides',price:799,description:'Crispy wings tossed in your choice of sauce.',image:'https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&w=700&q=85'},
{id:'cola',name:'Chilled Cola',category:'drinks',price:199,description:'The perfect cold pairing for your pizza.',image:'https://images.unsplash.com/photo-1629203849820-fdd70d49c38e?auto=format&fit=crop&w=700&q=85'},
{id:'brownie',name:'Fudge Brownie',category:'dessert',price:399,description:'Warm chocolate brownie with a soft centre.',image:'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=700&q=85'}];
let products=[...FALLBACK_PRODUCTS],cart=JSON.parse(localStorage.getItem('crust_cart')||'[]'),activeCategory='all',orderType='delivery';
const $=id=>document.getElementById(id);const money=n=>`Rs. ${Number(n).toLocaleString('en-PK')}`;const escapeHtml=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function saveCart(){localStorage.setItem('crust_cart',JSON.stringify(cart));}
function filteredProducts(){const q=($('menuSearch')?.value||'').toLowerCase();return products.filter(p=>(activeCategory==='all'||p.category===activeCategory)&&(!q||`${p.name} ${p.description}`.toLowerCase().includes(q)));}
function renderProducts(){const list=filteredProducts();$('menuGrid').innerHTML=list.map(p=>`<article class="menu-card"><div class="popular-tag ${p.popular?'':'hidden'}">Customer favourite</div><img class="menu-image" src="${p.image}" alt="${escapeHtml(p.name)}" loading="lazy"><div class="menu-info"><div class="menu-meta"><div><h3>${escapeHtml(p.name)}</h3><p class="menu-description">${escapeHtml(p.description)}</p><span class="menu-price">${money(p.price)}</span></div><button class="add-button" data-add="${p.id}" aria-label="Add ${escapeHtml(p.name)}">+</button></div></div></article>`).join('');$('emptyState').classList.toggle('hidden',list.length>0);document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>openCustomizer(b.dataset.add)));}
function renderCart(){const count=cart.reduce((n,i)=>n+i.qty,0),total=cart.reduce((n,i)=>n+i.price*i.qty,0);$('cartCount').textContent=count;$('cartTotal').textContent=money(total);$('cartEmpty').classList.toggle('hidden',cart.length>0);$('cartFooter').classList.toggle('hidden',cart.length===0);$('cartItems').innerHTML=cart.map(i=>`<div class="cart-line"><img src="${i.image}" alt=""><div class="cart-line-info"><strong>${escapeHtml(i.name)}</strong><span>${i.options?.join(', ')||'Classic recipe'}</span><div class="qty-control"><button data-qty="${i.key}" data-delta="-1" aria-label="Decrease quantity">−</button><span>${i.qty}</span><button data-qty="${i.key}" data-delta="1" aria-label="Increase quantity">+</button></div></div><span class="cart-line-price">${money(i.price*i.qty)}</span></div>`).join('');document.querySelectorAll('[data-qty]').forEach(b=>b.addEventListener('click',()=>changeQty(b.dataset.key,Number(b.dataset.delta))));}
function changeQty(key,delta){const item=cart.find(i=>i.key===key);if(!item)return;item.qty+=delta;if(item.qty<1)cart=cart.filter(i=>i.key!==key);saveCart();renderCart();}
function openDrawer(){$('cartDrawer').classList.add('open');$('drawerBackdrop').classList.add('open');$('cartDrawer').setAttribute('aria-hidden','false')}function closeDrawer(){$('cartDrawer').classList.remove('open');$('drawerBackdrop').classList.remove('open');$('cartDrawer').setAttribute('aria-hidden','true')}
function openCustomizer(id){const p=products.find(x=>x.id===id);if(!p)return;if(p.category!=='pizza'){addItem(p,[],p.price);return}$('customizerContent').innerHTML=`<p class="eyebrow">Make it yours</p><h2 id="customizerTitle">${escapeHtml(p.name)}</h2><img class="customizer-image" src="${p.image}" alt="${escapeHtml(p.name)}"><div class="choice-group"><h4>Choose your size</h4><label class="choice-row"><span><input type="radio" name="size" value="small" data-extra="0" checked> Small</span><span>10&quot;</span></label><label class="choice-row"><span><input type="radio" name="size" value="medium" data-extra="300"> Medium</span><span>+ Rs. 300</span></label><label class="choice-row"><span><input type="radio" name="size" value="large" data-extra="600"> Large</span><span>+ Rs. 600</span></label></div><div class="choice-group"><h4>Extra toppings</h4><label class="choice-row"><span><input type="checkbox" value="Extra cheese" data-extra="250"> Extra cheese</span><span>+ Rs. 250</span></label><label class="choice-row"><span><input type="checkbox" value="Jalapeños" data-extra="180"> Jalapeños</span><span>+ Rs. 180</span></label></div><button class="button button-primary full-width customizer-add" id="customizerAdd">Add to order <span>${money(p.price)}</span></button>`;$('customizerBackdrop').classList.remove('hidden');$('customizerAdd').addEventListener('click',()=>{const size=document.querySelector('input[name=size]:checked'),toppings=[...document.querySelectorAll('.choice-group input[type=checkbox]:checked')],extras=Number(size.dataset.extra)+toppings.reduce((n,x)=>n+Number(x.dataset.extra),0);addItem(p,[size.value,...toppings.map(x=>x.value)],p.price+extras);$('customizerBackdrop').classList.add('hidden');});}
function addItem(p,options,price){const key=`${p.id}-${options.join('-')||'classic'}`;const item=cart.find(i=>i.key===key);if(item)item.qty++;else cart.push({key,id:p.id,name:p.name,price,image:p.image,options,qty:1});saveCart();renderCart();showToast(`${p.name} added to your order`);}
function showToast(message){$('toast').textContent=message;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2400)}
async function loadFirestoreProducts(){const rid=new URLSearchParams(location.search).get('restaurant');if(!rid||typeof db==='undefined')return;try{const snap=await db.collection('restaurants').doc(rid).collection('products').where('active','!=',false).get();if(!snap.empty){products=snap.docs.map(d=>({id:d.id,...d.data(),image:d.data().image||FALLBACK_PRODUCTS[0].image,category:d.data().category||'pizza'}));renderProducts();showToast('Live menu loaded');}}catch(error){console.warn('[v0] Live menu unavailable, using starter menu',error.message)}}
async function placeOrder(e){e.preventDefault();if(!cart.length)return;const btn=$('placeOrderButton');btn.disabled=true;btn.textContent='Sending order…';const data={customerName:$('customerName').value.trim(),customerPhone:$('customerPhone').value.trim(),address:$('checkoutAddress').value.trim(),orderType,paymentMethod:$('paymentMethod').value};const items=cart.map(i=>({productId:i.id,name:i.name,qty:i.qty,price:i.price,options:i.options||[]}));const total=cart.reduce((n,i)=>n+i.price*i.qty,0);const payload={...data,items,total,status:'new',source:'online',createdAt:typeof FieldValue!=='undefined'?FieldValue.serverTimestamp():new Date().toISOString()};try{const rid=new URLSearchParams(location.search).get('restaurant');if(rid&&typeof auth!=='undefined'&&typeof DB!=='undefined'){if(!auth.currentUser)await auth.signInAnonymously();DB.init(rid);await DB.createOrder(payload);}else if(typeof db!=='undefined'){await db.collection('onlineOrders').add(payload);}const orderNumber=`CC-${String(Date.now()).slice(-6)}`;$('checkoutBackdrop').classList.add('hidden');closeDrawer();cart=[];saveCart();renderCart();$('checkoutForm').reset();showToast(`Order ${orderNumber} is on its way to the kitchen`);}catch(error){console.error('[v0] Order placement failed',error);showToast('Could not place order. Please try again.')}finally{btn.disabled=false;btn.innerHTML='Place order <span>→</span>';}}
document.addEventListener('DOMContentLoaded',()=>{renderProducts();renderCart();loadFirestoreProducts();document.querySelectorAll('.category-tab').forEach(b=>b.addEventListener('click',()=>{activeCategory=b.dataset.category;document.querySelectorAll('.category-tab').forEach(x=>x.classList.toggle('active',x===b));renderProducts()}));$('menuSearch').addEventListener('input',renderProducts);$('cartTrigger').addEventListener('click',openDrawer);$('cartClose').addEventListener('click',closeDrawer);$('drawerBackdrop').addEventListener('click',closeDrawer);$('customizerClose').addEventListener('click',()=>$('customizerBackdrop').classList.add('hidden'));$('checkoutClose').addEventListener('click',()=>$('checkoutBackdrop').classList.add('hidden'));document.querySelectorAll('.order-type-button').forEach(b=>b.addEventListener('click',()=>{orderType=b.dataset.type;document.querySelectorAll('.order-type-button').forEach(x=>x.classList.toggle('active',x===b));$('addressField')?.classList.toggle('hidden',orderType==='pickup')}));$('checkoutButton').addEventListener('click',()=>{if(orderType==='delivery'&&!$('customerAddress').value.trim()){showToast('Please add a delivery address');return}$('checkoutAddress').value=$('customerAddress').value;$('checkoutBackdrop').classList.remove('hidden')});$('checkoutForm').addEventListener('submit',placeOrder);$('dealButton').addEventListener('click',()=>{const a=products.find(p=>p.id==='firehouse'),b=products.find(p=>p.id==='garden');if(a)addItem(a,['medium'],a.price+300);if(b)addItem(b,['medium'],b.price+300);openDrawer()})});
